[package]
name = "enge-native"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[features]
rubberband = ["dep:rubberband-sys"]

[dependencies]
numpy = "0.29"
pyo3 = { version = "0.29", features = ["extension-module"] }
rtrb = "0.4.0"
rubberband-sys = { version = "0.1.4", optional = true }
