[project]
name = "enge"
version = "0.1.0"
description = "🚂 an audio synthesizer engine in Python and Rust 🚂"
readme = "README.md"
authors = [
    { name = "Tom Ritchford", email = "tom@swirly.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pydantic>=2.13.4",
    "ufor",
]

[build-system]
requires = ["maturin>=1.9,<2"]
build-backend = "maturin"

[tool.maturin]
python-source = "src"
module-name = "enge._native"

[tool.uv.sources]
ufor = { git = "https://github.com/rec/ufor.git", branch = "main" }
reccy = { git = "https://github.com/rec/reccy.git", branch = "main" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "reccy",
]
